## NumPy Fundamentals
This exercise practices creating and working with NumPy arrays, checking their data types, transposing arrays, slicing values, and building arrays with multiple dimensions.


In [1]:
import numpy as np

## Array Basics

In [2]:
fruits = ["apple", "banana","cherry", "date"]
print(fruits)

['apple', 'banana', 'cherry', 'date']


In [3]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [4]:
print(arr_1.dtype)
# The dtype is the data type of the values in the array.
# The number means the maximum string length in the array.
# Here 6 comes from the longest word, such as "banana" or "cherry"

<U6


In [5]:
arr_2 = np.array([(10, 11, 12), (13, 14, 15)])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [6]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [7]:
print(arr_2)

# No, arr_2 itself is not changed by using arr_2.T.
# arr_2.T only shows a transposed view of the array.


[[10 11 12]
 [13 14 15]]


In [8]:
arr_3 = np.array([(1, 3, 5), (2, 4, 6)])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [9]:
arr_4 = np.array([arr_3[0,2], arr_3[1,1]])
print(arr_4)

[5 4]


In [11]:
arr_5 = np.ones((2, 2, 2))
print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
