## Exercise 1.B NumPy Random

In [2]:
import numpy as np

## Generating random numbers

In [3]:
r_1 = np.random.randint(1, 21, size=2)
print(r_1)

[ 9 14]


In [5]:
r_2 = np.random.randint(1,21, size=(1,2))
print(r_2)

[[ 2 19]]


In [8]:
r_3 = np.random.random((2,1))
print(r_3)

[[0.62763388]
 [0.56642748]]


In [10]:
r_4 = np.random.randint(20,101, size=(4,5))
print(r_4)

[[57 64 66 24 80]
 [70 96 94 79 29]
 [45 32 23 32 85]
 [57 23 46 79 73]]


In [11]:
r_5 = np.random.random((4, 5))
print(r_5)

[[0.32820338 0.46449944 0.28101396 0.25803629 0.9328181 ]
 [0.54430673 0.45723613 0.64816177 0.87296547 0.33096503]
 [0.19607037 0.94501704 0.07070694 0.42531829 0.1171506 ]
 [0.35079465 0.59205181 0.02657972 0.01012853 0.52423154]]


## Generating random choices from an array

In [12]:
students = np.array(["jessica","cagla","rodas", "kidus",
    "sultan", "longley", "kiki", "angel",
    "tracy", "fuat", "onur", "shay"
])

print(students)

['jessica' 'cagla' 'rodas' 'kidus' 'sultan' 'longley' 'kiki' 'angel'
 'tracy' 'fuat' 'onur' 'shay']


In [17]:
call_on = np.random.choice(students)
print(call_on)

cagla


In [20]:
breakout_groups = np.random.choice(students, size=(3,4))
print(breakout_groups)

# This may not be the best way to assign breakout groups because
# the same student can appear more than once and some students may not appear at all.

[['angel' 'jessica' 'angel' 'kiki']
 ['angel' 'longley' 'shay' 'longley']
 ['tracy' 'kiki' 'kidus' 'cagla']]


In [21]:
call_on_weighted = np.random.choice(
    students,
    size=5,
    p=[0.30, 0.10, 0.08, 0.07, 0.06, 0.05, 0.09, 0.00, 0.07, 0.06, 0.06, 0.06]
)
print(call_on_weighted)  
# p values:
# jessica = 0.30
# cagla = 0.10
# rodas = 0.08
# kidus = 0.07
# sultan = 0.06
# longley = 0.05
# kiki = 0.09
# angel = 0.00
# tracy = 0.07
# fuat = 0.06
# onur = 0.06
# shay = 0.06


['fuat' 'rodas' 'jessica' 'cagla' 'cagla']


## Generating a Normal Distribution

In [24]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4,5))
print(bell_curve)

[[14.38599506  7.06651615  6.17463659  9.88652652  2.83426479]
 [ 8.15409108  1.36074644  8.1268253  14.06196122  5.27165064]
 [ 7.48417943 11.68289984  0.28217753  9.14420361  1.87483158]
 [ 5.30145023 11.43032223 10.77512064  3.77924191 11.75931212]]
7.541847645477462


In [25]:
print(np.mean(bell_curve))

7.541847645477462
