# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

## Looping through arrays

In [6]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [7]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [10]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The first loop goes through the first dimension of the array, so it works with one full row at a time and prints each row multiplied by 2. The second loop goes through the second dimension, so it works with one individual number at a time and prints each value multiplied by 2 separately.


In [11]:
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

# This result is different because x represents a full row, not a single number.
# So x * 2 doubles the whole row each time, and since it is inside the inner loop,
# the same doubled row gets printed once for each value in that row.

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking arrays

In [13]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [14]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [16]:
stacked_array_1 = np.stack((joined_array_1,joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [17]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2)
# This gives an error because the two arrays do not have the same shape.
# np.stack() requires all input arrays to be exactly the same size and dimensions.

ValueError: all input arrays must have the same shape

In [18]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [19]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
print(another_2)

# This gives an error because the arrays do not have the same number of rows.
# To concatenate on axis=1, the arrays must match in size along axis=0

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [26]:
horizontal_stack = np.hstack((arrA,arrA))
print(horizontal_stack) 
# hstack joins the arrays side by side by adding more columns.

vertical_stack = np.vstack((arrA,arrA))
print(vertical_stack)     

# vstack joins the arrays on top of each other by adding more rows.

depth_stack = np.dstack((arrA, arrA))
print(depth_stack)  

# dstack stacks the arrays along a third dimension, adding depth.


[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splititng arrays

In [28]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

# This creates 2 arrays.
# Each result is still a 2-dimensional array.
# Since joined_array_1 has 4 rows, each split gets 2 rows.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [31]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)
# This creates 3 arrays.
# Each result is still a 2-dimensional array.
# Because 4 rows cannot be split evenly into 3 parts

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Arrays Values

In [33]:
result_1 = np.where(arrA % 2 == 0, arrA,  'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [36]:
arr_B = np.array([[7,6], [13,5], [7,3]])
arr_B_sorted = np.sort(arr_B)
print(arr_B_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [43]:
arr_B = np.array([[7,6], [13,5], [7,3]])
arr_B_sorted = np.sort(arr_B)
print(arr_B_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [46]:
print(arr_B)
z = arr_B < 7
arrC = arr_B[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [ ]:
y = arrB >= 7
arrD = arrB[y]
