In [1]:
import numpy as np

## Sample arrays

In [2]:
r_1 = np.random.randint(1, 21, size=2)
r_2 = np.random.randint(1, 21, size=(1, 2))
r_3 = np.random.random((2, 1))
r_4 = np.random.randint(20, 101, size=(4, 5))
r_5 = np.random.random((4, 5))

print("r_1 =", r_1)
print("r_2 =\n", r_2)
print("r_3 =\n", r_3)
print("r_4 =\n", r_4)
print("r_5 =\n", r_5)


r_1 = [20  1]
r_2 =
 [[16  4]]
r_3 =
 [[0.02331741]
 [0.17695152]]
r_4 =
 [[39 27 33 28 24]
 [91 89 71 57 38]
 [25 34 25 25 28]
 [87 21 40 46 41]]
r_5 =
 [[0.30895023 0.93174645 0.13816367 0.47252166 0.38409947]
 [0.13286643 0.06710979 0.28623229 0.09877124 0.16373813]
 [0.16639817 0.70143961 0.27274144 0.77598829 0.07738012]
 [0.74003088 0.51856522 0.14262465 0.37704922 0.59535038]]


## Permutaions

In [3]:
print(r_4)

[[39 27 33 28 24]
 [91 89 71 57 38]
 [25 34 25 25 28]
 [87 21 40 46 41]]


In [4]:
np.random.shuffle(r_4)
print(r_4)

[[39 27 33 28 24]
 [87 21 40 46 41]
 [91 89 71 57 38]
 [25 34 25 25 28]]


The rows of `r_4` were shuffled in place. The array changed directly, but the values inside each row stayed together.


In [5]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)
print(r_4)


[[87 21 40 46 41]
 [39 27 33 28 24]
 [91 89 71 57 38]
 [25 34 25 25 28]]
[[39 27 33 28 24]
 [87 21 40 46 41]
 [91 89 71 57 38]
 [25 34 25 25 28]]


I would use `shuffle` when I want to rearrange the original array itself. I would use `permutation` when I want a shuffled version without changing the original array.


## Mathematical Operations

In [7]:
print("r_1 =", r_1)
print("shape of r_1 =", r_1.shape)

print("r_2 =\n", r_2)
print("shape of r_2 =", r_2.shape)

result_1_2 = np.add(r_1, r_2)
print("r_1 + r_2 =", result_1_2)
print("shape of result =", result_1_2.shape)


r_1 = [20  1]
shape of r_1 = (2,)
r_2 =
 [[16  4]]
shape of r_2 = (1, 2)
r_1 + r_2 = [[36  5]]
shape of result = (1, 2)


In [8]:
print("r_1 =", r_1)
print("shape of r_1 =", r_1.shape)

print("r_3 =\n", r_3)
print("shape of r_3 =", r_3.shape)

result_1_3 = np.add(r_1, r_3)
print("r_1 + r_3 =\n", result_1_3)
print("shape of result =", result_1_3.shape)


r_1 = [20  1]
shape of r_1 = (2,)
r_3 =
 [[0.02331741]
 [0.17695152]]
shape of r_3 = (2, 1)
r_1 + r_3 =
 [[20.02331741  1.02331741]
 [20.17695152  1.17695152]]
shape of result = (2, 2)


In [9]:
print("r_2 =\n", r_2)
print("shape of r_2 =", r_2.shape)

print("r_4 =\n", r_4)
print("shape of r_4 =", r_4.shape)

result_2_4 = np.add(r_2, r_4)
print("r_2 + r_4 =\n", result_2_4)
print("shape of result =", result_2_4.shape)


r_2 =
 [[16  4]]
shape of r_2 = (1, 2)
r_4 =
 [[39 27 33 28 24]
 [87 21 40 46 41]
 [91 89 71 57 38]
 [25 34 25 25 28]]
shape of r_4 = (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [10]:
# r_1 + r_4 causes an error because their shapes are not compatible for broadcasting
np.add(r_1, r_4)


ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [11]:
# r_3 + r_4 also causes an error because their shapes are not compatible for broadcasting
np.add(r_3, r_4)


ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

In [12]:
# r_2 + r_4 causes an error because (1, 2) and (4, 5) do not match for broadcasting
np.add(r_2, r_4)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [13]:
print("r_4 =\n", r_4)
print(np.add(np.array([1]), r_4))


r_4 =
 [[39 27 33 28 24]
 [87 21 40 46 41]
 [91 89 71 57 38]
 [25 34 25 25 28]]
[[40 28 34 29 25]
 [88 22 41 47 42]
 [92 90 72 58 39]
 [26 35 26 26 29]]


In [14]:
print(np.add(np.array([[1]]), r_4))


[[40 28 34 29 25]
 [88 22 41 47 42]
 [92 90 72 58 39]
 [26 35 26 26 29]]


In [15]:
print(np.add(np.array([1, 1, 1, 1, 1]), r_4))


[[40 28 34 29 25]
 [88 22 41 47 42]
 [92 90 72 58 39]
 [26 35 26 26 29]]


In [16]:
# This produces an error because (2, 1) cannot broadcast to (4, 5)
np.add(np.array([[1], [1]]), r_4)


ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

Broadcasting is NumPy's way of making arrays with different shapes work together when possible. It compares shapes from right to left. Two dimensions are compatible if they are equal or if one of them is 1. When using `add`, NumPy adds matching values position by position after stretching any dimension of size 1 as needed. The resulting array shape is based on the broadcasted shape that both arrays can fit into.
